# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy to PyPI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install PIP
      run: |
        python -m pip install --upgrade pip
    - name: Setup Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Publish
      env:
        PYPI_USERNAME: ${{ secrets.pypi_user }}
        PYPI_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        make install
        make publish